//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//
// Generated by utils/build-list-format-data — do not edit by hand.
// CLDR version: 48.0
// Locales: all
// Fallback: root
//===----------------------------------------------------------------------===//

#include "InternationalizationDataMacros.h"

#if !FOUNDATION_LIST_FORMAT_ICU

#include <stdint.h>

// Row table. Each row is four indexes into _ListFormatPatterns.
typedef struct { uint16_t start; uint16_t middle; uint16_t end; uint16_t pair; } _ListFormatRow;

// Sparse slot entry: maps a locale (by index into _ListFormatLocales)
// to a row index. Entries are sorted by locale for binary search.
typedef struct { uint16_t locale; uint16_t row; } _ListFormatSlotEntry;

// Parent-locale entry: child and parent are indexes into _ListFormatLocales.
typedef struct { uint16_t child; uint16_t parent; } _ListFormatParentEntry;

static const uint16_t _ListFormatPatternCount = 344;
static const uint16_t _ListFormatRowCount = 295;
static const uint16_t _ListFormatLocaleCount = 329;
static const uint16_t _ListFormatSlot_AndWide_Count = 179;
static const uint16_t _ListFormatSlot_AndShort_Count = 184;
static const uint16_t _ListFormatSlot_AndNarrow_Count = 133;
static const uint16_t _ListFormatSlot_OrWide_Count = 150;
static const uint16_t _ListFormatSlot_OrShort_Count = 148;
static const uint16_t _ListFormatSlot_OrNarrow_Count = 149;
static const uint16_t _ListFormatParentCount = 141;
static const char * const _ListFormatFallbackLocale = "root";

// Pattern string pool. Rows reference these by index.
INTERNAL const char * const _ListFormatPatterns[344];

// Row table. Each row is four indexes into _ListFormatPatterns.
INTERNAL const _ListFormatRow _ListFormatRows[295];

// Locale string pool. Slot and parent entries reference these by index.
INTERNAL const char * const _ListFormatLocales[329];

// Sparse slot tables, one per (type, width), sorted by locale.
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_AndWide[179];
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_AndShort[184];
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_AndNarrow[133];
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_OrWide[150];
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_OrShort[148];
INTERNAL const _ListFormatSlotEntry _ListFormatSlot_OrNarrow[149];

// Parent-locale map (explicit CLDR <parentLocales> overrides), sorted by child.
INTERNAL const _ListFormatParentEntry _ListFormatParents[141];

#endif // !FOUNDATION_LIST_FORMAT_ICU
