//===----------------------------------------------------------------------===//
//
// This source file is part of the Swift.org open source project
//
// Copyright (c) 2026 Apple Inc. and the Swift project authors
// Licensed under Apache License v2.0 with Runtime Library Exception
//
// See https://swift.org/LICENSE.txt for license information
// See https://swift.org/CONTRIBUTORS.txt for the list of Swift project authors
//
//===----------------------------------------------------------------------===//

/*

 Codable schema for ListFormatData.json — the intermediate form between
 CLDR XML (stage 1, generated by utils/update-list-format-data) and the
 packed C header (stage 2, generated by utils/build-list-format-data).

 Both stages compile this file alongside their own impl. Keeping the schema
 in one place means Swift's Codable handles encode/decode correctness; if
 the format changes, both ends see it immediately.

 */

import Foundation

/// A `TextOutputStream` over standard error, so the generators can use
/// `print(..., to: &standardError)` for progress/diagnostics instead of the
/// more verbose `FileHandle.standardError.write(...data(using:)...)`.
struct StandardError: TextOutputStream {
    mutating func write(_ string: String) {
        guard let data = string.data(using: .utf8) else { return }
        FileHandle.standardError.write(data)
    }
}
var standardError = StandardError()

internal struct ListFormatDataSchema: Codable {
    /// Human-readable provenance string (e.g. "CLDR 48.0"). Echoed into the
    /// generated C header's leading comment for traceability.
    let generatedFrom: String

    /// The canonical CLDR version this data was extracted from.
    let cldrVersion: String

    /// Global pool of unique pattern strings. Rows reference these by index.
    let patterns: [String]

    /// Global pool of unique pattern combinations. Slots reference these by index.
    let rows: [Row]

    /// Per-slot sparse map: slot name (e.g. "and_wide") → locale → row index.
    /// Slot names use snake_case for JSON-friendliness; the canonical names are
    /// listed in `listFormatSlotNames` below.
    let slots: [String: [String: Int]]

    /// Explicit CLDR <parentLocales> chain after greedy simplification.
    /// Truncation parents (en_AU → en) are recovered at runtime from the
    /// locale string itself; only non-truncation overrides ship.
    let parents: [String: String]

    /// One row of resolved patterns, indexed into the global `patterns` pool.
    internal struct Row: Codable, Hashable {
        let start: Int
        let middle: Int
        let end: Int
        let pair: Int
    }
}

/// The fixed set of slot names. Order is significant — stage 2 uses this
/// order when packing slots into the C header.
internal let listFormatSlotNames: [String] = [
    "and_wide", "and_short", "and_narrow",
    "or_wide",  "or_short",  "or_narrow",
]
